
name: Build aarch64-unknown-linux-musl

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      # Create Cross.toml with rustls configuration
      - name: Configure Cross.toml
        run: |
          cat > Cross.toml << 'EOF'
          [target.aarch64-unknown-linux-musl]
          image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"
          EOF

      - name: Build
        run: cross build --target aarch64-unknown-linux-musl --release
        env:
          DOCKER_BUILDKIT: 1
          CARGO_BUILD_RUSTFLAGS: "-C target-feature=+crt-static"
          RUSTLS_USE_SYSTEM_ROOT_CERTS: "0"
          REQWEST_NO_NATIVE_TLS: "1"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-unknown-linux-musl
          path: target/aarch64-unknown-linux-musl/release/markov-chains-bot
